apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-sandbox
  labels:
    app: devops-sandbox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-sandbox
  template:
    metadata:
      labels:
        app: devops-sandbox
    spec:
      containers:
      - name: devops-sandbox-container
        image: 520291287938.dkr.ecr.us-east-1.amazonaws.com/devops-app:v1.0.3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: devops-sandbox-service
spec:
  type: LoadBalancer
  selector:
    app: devops-sandbox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

