name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        cd devops_app
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        cd devops_app
        flake8 .
        
    - name: Run tests
      run: |
        cd devops_app
        pytest
    
    - name: Build Docker Image
      run: |
        docker build -t sandbox -f Dockerfile .
        
